# Generated by Django 2.1 on 2018-12-17 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Задача')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('on_pause', 'На паузе'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='День рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('issues', models.ManyToManyField(blank=True, related_name='programmers', to='webapp.Issue', verbose_name='Задачи')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, verbose_name='Проект')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='webapp.Programmer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='webapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='programmer',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='programmers', through='webapp.Work', to='webapp.Project', verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='programmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
